# Generated by Django 5.2.17 on 2026-09-04 16:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Trading Account', max_length=100)),
                ('mode', models.CharField(choices=[('paper', 'Paper Trading'), ('live', 'Live Trading')], default='paper', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=80, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('min_order_quantity', models.DecimalField(decimal_places=18, default=Decimal('1E-8'), max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_order_quantity', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_precision', models.PositiveSmallIntegerField(default=8)),
                ('quantity_precision', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_trading_pairs', to='market.marketasset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_trading_pairs', to='market.marketasset')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('limit_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('filled_quantity', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('average_fill_price', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.tradingaccount')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.tradingpair')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price', models.DecimalField(decimal_places=18, max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fee', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fee_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_fees', to='market.marketasset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.order')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['order', '-executed_at'], name='trading_tra_order_i_60bec8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('locked', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=40, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='trading.tradingaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_balances', to='market.marketasset')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'asset'], name='trading_tra_account_d22d71_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'asset'), name='unique_trading_account_asset')],
            },
        ),
        migrations.AddConstraint(
            model_name='tradingpair',
            constraint=models.UniqueConstraint(fields=('base_asset', 'quote_asset'), name='unique_trading_pair'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account', '-created_at'], name='trading_ord_account_e4ff2c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['pair', 'status'], name='trading_ord_pair_id_3fe82d_idx'),
        ),
    ]
