# Generated by Django 5.2.17 on 2026-09-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('coingecko_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('chain', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('contract_address', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('decimals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['symbol'], name='market_mark_symbol_9cf88f_idx'), models.Index(fields=['chain', 'contract_address'], name='market_mark_chain_e83b84_idx'), models.Index(fields=['is_active'], name='market_mark_is_acti_b7638c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=12, max_digits=30)),
                ('market_cap_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=12, max_digits=40, null=True)),
                ('fully_diluted_valuation_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.marketasset')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['asset', '-captured_at'], name='market_mark_asset_i_6f5d97_idx'), models.Index(fields=['captured_at'], name='market_mark_capture_aa8052_idx')],
            },
        ),
    ]
