# Generated by Django 5.2.17 on 2026-08-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(default='ethereum', max_length=50)),
                ('contract_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('decimals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('liquidity_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('market_cap_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('holder_count', models.PositiveIntegerField(blank=True, null=True)),
                ('top_10_holder_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('buy_count_24h', models.PositiveIntegerField(default=0)),
                ('sell_count_24h', models.PositiveIntegerField(default=0)),
                ('contract_verified', models.BooleanField(default=False)),
                ('unlimited_mint_detected', models.BooleanField(default=False)),
                ('blacklist_detected', models.BooleanField(default=False)),
                ('liquidity_locked', models.BooleanField(default=False)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['chain', 'first_seen_at'], name='token_scann_chain_0d2fb0_idx'), models.Index(fields=['risk_score'], name='token_scann_risk_sc_e680d2_idx')],
            },
        ),
    ]
