# Generated by Django 5.2.17 on 2026-08-26 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='risk_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='TokenAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('new_token', 'New Token'), ('holder_growth', 'Holder Growth'), ('volume_spike', 'Volume Spike'), ('liquidity_change', 'Liquidity Change'), ('demand_increase', 'Demand Increase'), ('risk_change', 'Risk Score Change'), ('contract_warning', 'Contract Warning'), ('liquidity_warning', 'Liquidity Warning')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='token_scanner.token')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', '-created_at'], name='token_scann_token_i_b867df_idx'), models.Index(fields=['severity', '-created_at'], name='token_scann_severit_b9df94_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('liquidity_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('market_cap_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('holder_count', models.PositiveIntegerField(blank=True, null=True)),
                ('top_10_holder_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('buy_count_24h', models.PositiveIntegerField(default=0)),
                ('sell_count_24h', models.PositiveIntegerField(default=0)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='token_scanner.token')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['token', '-scanned_at'], name='token_scann_token_i_22184a_idx')],
            },
        ),
    ]
