# Generated by Django 5.2.17 on 2026-09-09 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_scanner', '0002_alter_token_risk_score_tokenalert_tokenscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenscan',
            name='from_block',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenscan',
            name='observation_block_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenscan',
            name='observation_quality',
            field=models.CharField(blank=True, choices=[('LIMITED', 'Limited'), ('STANDARD', 'Standard'), ('EXTENDED', 'Extended')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tokenscan',
            name='to_block',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='top_10_holder_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='tokenscan',
            index=models.Index(fields=['observation_quality', '-scanned_at'], name='token_scann_observa_041793_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenscan',
            index=models.Index(fields=['from_block', 'to_block'], name='token_scann_from_bl_5851cb_idx'),
        ),
    ]
