# Generated by Django 5.2.17 on 2026-08-10 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('chain_id', models.CharField(blank=True, max_length=100)),
                ('network_type', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20)),
                ('rpc_url', models.URLField(blank=True)),
                ('explorer_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blockchain Network',
                'verbose_name_plural': 'Blockchain Networks',
                'db_table': 'blockchain_network',
                'ordering': ['name'],
            },
        ),
    ]
