# Generated by Django 5.2.17 on 2026-08-10 14:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchainnetwork',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='blockchainnetwork',
            name='network_type',
        ),
        migrations.AddField(
            model_name='blockchainnetwork',
            name='is_testnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='chain_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='blockchainnetwork',
            table='blockchain_networks',
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('token_standard', models.CharField(choices=[('native', 'Native'), ('erc20', 'ERC-20'), ('trc20', 'TRC-20'), ('bep20', 'BEP-20'), ('spl', 'SPL')], default='native', max_length=20)),
                ('contract_address', models.CharField(blank=True, max_length=255)),
                ('decimals', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(36)])),
                ('is_native', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='blockchain.blockchainnetwork')),
            ],
            options={
                'db_table': 'blockchain_assets',
                'ordering': ['network', 'symbol'],
                'indexes': [models.Index(fields=['network', 'symbol'], name='asset_network_symbol_idx'), models.Index(fields=['contract_address'], name='asset_contract_idx')],
                'constraints': [models.UniqueConstraint(fields=('network', 'symbol', 'contract_address'), name='unique_network_asset_contract')],
            },
        ),
    ]
