# Generated by Django 5.2.17 on 2026-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_blockchainnetwork_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchainnetwork',
            options={'ordering': ['name'], 'verbose_name': 'Blockchain Network', 'verbose_name_plural': 'Blockchain Networks'},
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='is_testnet',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
