# Generated by Django 5.2.17 on 2026-09-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_blockchainnetwork_options_and_more'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMarketMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blockchain_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_mappings', to='blockchain.asset')),
                ('market_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_mappings', to='market.marketasset')),
            ],
            options={
                'db_table': 'asset_market_mappings',
                'ordering': ['market_asset', 'blockchain_asset'],
                'indexes': [models.Index(fields=['market_asset', 'is_active'], name='mapping_market_active_idx'), models.Index(fields=['blockchain_asset', 'is_active'], name='mapping_blockchain_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('market_asset', 'blockchain_asset'), name='unique_asset_market_mapping')],
            },
        ),
    ]
