"""
HappyWallet Token Scanner - Persistence Service.

Persists real, read-only scanner observations into:

    Token
        ↓
    TokenScan
        ↓
    TokenAlert

Security rules:
    - Never store private keys.
    - Never store seed phrases or mnemonics.
    - Never sign transactions.
    - Never submit transactions.
    - Never execute swaps.
    - Never automatically buy or sell tokens.

Only observed public blockchain analysis is persisted.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Any

from django.db import transaction

from ..models import Token, TokenAlert, TokenScan
from .scanner import TokenScanResult


@dataclass(frozen=True)
class PersistenceResult:
    """Database objects created or updated by one scanner persistence run."""

    token: Token
    scan: TokenScan
    alerts: tuple[TokenAlert, ...]


class TokenScanPersistence:
    """
    Persist a real TokenScanResult.

    The service does not perform blockchain calls itself. It only persists
    observations already produced by the read-only scanner.
    """

    @transaction.atomic
    def persist(
        self,
        result: TokenScanResult,
    ) -> PersistenceResult:
        """
        Persist one complete scanner result atomically.

        A Token is created or updated, one immutable TokenScan snapshot is
        created, and alerts are generated by comparing the new observation
        against the immediately preceding scan.
        """

        token, created = Token.objects.get_or_create(
            contract_address=result.token_address,
            defaults={
                "chain": "ethereum",
                "name": result.name or "",
                "symbol": result.symbol or "",
                "decimals": result.decimals,
            },
        )

        previous_scan = (
            TokenScan.objects
            .filter(token=token)
            .order_by("-scanned_at")
            .first()
        )

        self._update_token(
            token=token,
            result=result,
        )

        scan = self._create_scan(
            token=token,
            result=result,
        )

        alerts = self._create_alerts(
            token=token,
            result=result,
            previous_scan=previous_scan,
            is_new_token=created,
        )

        return PersistenceResult(
            token=token,
            scan=scan,
            alerts=tuple(alerts),
        )

    # =========================================================================
    # Token
    # =========================================================================

    @staticmethod
    def _update_token(
        *,
        token: Token,
        result: TokenScanResult,
    ) -> None:
        """
        Update the current Token record using observed scanner data only.
        """

        token.chain = token.chain or "ethereum"

        if result.name:
            token.name = result.name

        if result.symbol:
            token.symbol = result.symbol

        if result.decimals is not None:
            token.decimals = result.decimals

        token.contract_verified = bool(
            result.contract.verified
        )

        token.unlimited_mint_detected = bool(
            result.contract.unlimited_mint_detected
        )

        token.blacklist_detected = bool(
            result.contract.blacklist_function_detected
        )

        # The current liquidity analyzer does not have a genuine lock
        # verification provider. Never claim that liquidity is locked.
        token.liquidity_locked = False

        token.liquidity_usd = _decimal_or_none(
            result.liquidity.total_liquidity_usd
        )

        token.holder_count = _integer_or_none(
            result.holders.holder_count
        )

        token.top_10_holder_percentage = _decimal_or_none(
            result.holders.top_10_holder_percentage
        )

        token.buy_count_24h = _non_negative_int(
            result.demand.buy_count
        )

        token.sell_count_24h = _non_negative_int(
            result.demand.sell_count
        )

        token.risk_score = _risk_score_or_none(
            result.risk.score
        )

        token.last_scanned_at = None

        # last_scanned_at is deliberately populated by the database timestamp
        # on the TokenScan below. The save is followed by an explicit update.
        token.save()

    # =========================================================================
    # Historical scan
    # =========================================================================

    @staticmethod
    def _create_scan(
        *,
        token: Token,
        result: TokenScanResult,
    ) -> TokenScan:
        """Create an immutable historical snapshot."""

        scan = TokenScan.objects.create(
            token=token,
            liquidity_usd=_decimal_or_none(
                result.liquidity.total_liquidity_usd
            ),
            # Market cap is not currently produced by the scanner.
            market_cap_usd=None,
            # 24h USD volume is not currently produced by the scanner.
            volume_24h_usd=None,
            holder_count=_integer_or_none(
                result.holders.holder_count
            ),
            top_10_holder_percentage=_decimal_or_none(
                result.holders.top_10_holder_percentage
            ),
            buy_count_24h=_non_negative_int(
                result.demand.buy_count
            ),
            sell_count_24h=_non_negative_int(
                result.demand.sell_count
            ),
            risk_score=_risk_score_or_none(
                result.risk.score
            ),
        )

        token.last_scanned_at = scan.scanned_at
        token.save(
            update_fields=[
                "last_scanned_at",
            ]
        )

        return scan

    # =========================================================================
    # Alerts
    # =========================================================================

    def _create_alerts(
        self,
        *,
        token: Token,
        result: TokenScanResult,
        previous_scan: TokenScan | None,
        is_new_token: bool,
    ) -> list[TokenAlert]:
        """Create alerts based only on observed scanner conditions."""

        alerts: list[TokenAlert] = []

        if is_new_token:
            alerts.append(
                self._alert(
                    token=token,
                    alert_type=TokenAlert.AlertType.NEW_TOKEN,
                    severity=TokenAlert.Severity.INFO,
                    title="New token discovered",
                    message=(
                        f"{result.symbol or result.token_address} "
                        "was newly discovered by the scanner."
                    ),
                    data={
                        "contract_address": result.token_address,
                        "symbol": result.symbol or None,
                        "name": result.name or None,
                    },
                )
            )

        alerts.extend(
            self._contract_alerts(
                token=token,
                result=result,
            )
        )

        alerts.extend(
            self._liquidity_alerts(
                token=token,
                result=result,
                previous_scan=previous_scan,
            )
        )

        alerts.extend(
            self._holder_alerts(
                token=token,
                result=result,
                previous_scan=previous_scan,
            )
        )

        alerts.extend(
            self._demand_alerts(
                token=token,
                result=result,
            )
        )

        alerts.extend(
            self._risk_alerts(
                token=token,
                result=result,
                previous_scan=previous_scan,
            )
        )

        return alerts

    @staticmethod
    def _contract_alerts(
        *,
        token: Token,
        result: TokenScanResult,
    ) -> list[TokenAlert]:
        alerts: list[TokenAlert] = []

        contract = result.contract

        if contract.unlimited_mint_detected:
            alerts.append(
                TokenScanPersistence._alert(
                    token=token,
                    alert_type=TokenAlert.AlertType.CONTRACT_WARNING,
                    severity=TokenAlert.Severity.CRITICAL,
                    title="Mint capability detected",
                    message=(
                        "The contract analyzer detected a mint-related "
                        "function selector. This is a heuristic finding "
                        "and does not by itself prove unrestricted minting."
                    ),
                    data={
                        "unlimited_mint_detected": True,
                        "evidence": "bytecode selector heuristic",
                    },
                )
            )

        if contract.blacklist_function_detected:
            alerts.append(
                TokenScanPersistence._alert(
                    token=token,
                    alert_type=TokenAlert.AlertType.CONTRACT_WARNING,
                    severity=TokenAlert.Severity.CRITICAL,
                    title="Blacklist capability detected",
                    message=(
                        "The contract analyzer detected a blacklist-related "
                        "function selector. This is a heuristic finding and "
                        "does not by itself prove malicious behavior."
                    ),
                    data={
                        "blacklist_detected": True,
                        "evidence": "bytecode selector heuristic",
                    },
                )
            )

        return alerts

    @staticmethod
    def _liquidity_alerts(
        *,
        token: Token,
        result: TokenScanResult,
        previous_scan: TokenScan | None,
    ) -> list[TokenAlert]:
        alerts: list[TokenAlert] = []

        liquidity = result.liquidity

        if liquidity.is_thin_liquidity:
            alerts.append(
                TokenScanPersistence._alert(
                    token=token,
                    alert_type=TokenAlert.AlertType.LIQUIDITY_WARNING,
                    severity=TokenAlert.Severity.WARNING,
                    title="Thin liquidity",
                    message=(
                        "Observed liquidity is below the scanner's "
                        "thin-liquidity threshold."
                    ),
                    data={
                        "liquidity_usd": _json_decimal(
                            liquidity.total_liquidity_usd
                        ),
                    },
                )
            )

        if (
            previous_scan is not None
            and previous_scan.liquidity_usd is not None
            and liquidity.total_liquidity_usd is not None
        ):
            old = Decimal(previous_scan.liquidity_usd)
            new = Decimal(liquidity.total_liquidity_usd)

            if old > 0:
                change_pct = ((new - old) / old) * Decimal("100")

                if abs(change_pct) >= Decimal("20"):
                    severity = (
                        TokenAlert.Severity.CRITICAL
                        if change_pct <= Decimal("-50")
                        else TokenAlert.Severity.WARNING
                    )

                    direction = (
                        "increased"
                        if change_pct > 0
                        else "decreased"
                    )

                    alerts.append(
                        TokenScanPersistence._alert(
                            token=token,
                            alert_type=TokenAlert.AlertType.LIQUIDITY_CHANGE,
                            severity=severity,
                            title="Liquidity changed",
                            message=(
                                f"Observed liquidity {direction} by "
                                f"{abs(change_pct):.2f}% since the previous scan."
                            ),
                            data={
                                "previous_liquidity_usd": _json_decimal(old),
                                "current_liquidity_usd": _json_decimal(new),
                                "change_percentage": _json_decimal(change_pct),
                            },
                        )
                    )

        return alerts

    @staticmethod
    def _holder_alerts(
        *,
        token: Token,
        result: TokenScanResult,
        previous_scan: TokenScan | None,
    ) -> list[TokenAlert]:
        alerts: list[TokenAlert] = []

        current = result.holders.holder_count

        if (
            previous_scan is not None
            and previous_scan.holder_count is not None
            and current is not None
            and current > previous_scan.holder_count
        ):
            growth = current - previous_scan.holder_count

            alerts.append(
                TokenScanPersistence._alert(
                    token=token,
                    alert_type=TokenAlert.AlertType.HOLDER_GROWTH,
                    severity=TokenAlert.Severity.INFO,
                    title="Holder count increased",
                    message=(
                        f"Observed holder count increased by {growth} "
                        "since the previous scan."
                    ),
                    data={
                        "previous_holder_count": previous_scan.holder_count,
                        "current_holder_count": current,
                        "growth": growth,
                    },
                )
            )

        return alerts

    @staticmethod
    def _demand_alerts(
        *,
        token: Token,
        result: TokenScanResult,
    ) -> list[TokenAlert]:
        alerts: list[TokenAlert] = []

        demand = result.demand

        if demand.demand_pressure is not None:
            pressure = Decimal(str(demand.demand_pressure))

            if pressure >= Decimal("50"):
                alerts.append(
                    TokenScanPersistence._alert(
                        token=token,
                        alert_type=TokenAlert.AlertType.DEMAND_INCREASE,
                        severity=TokenAlert.Severity.INFO,
                        title="Strong observed buying pressure",
                        message=(
                            "Recent Transfer activity shows strong "
                            "observed buying pressure."
                        ),
                        data={
                            "demand_pressure": _json_decimal(pressure),
                            "buy_count": _non_negative_int(
                                demand.buy_count
                            ),
                            "sell_count": _non_negative_int(
                                demand.sell_count
                            ),
                        },
                    )
                )

        return alerts

    @staticmethod
    def _risk_alerts(
        *,
        token: Token,
        result: TokenScanResult,
        previous_scan: TokenScan | None,
    ) -> list[TokenAlert]:
        alerts: list[TokenAlert] = []

        current = result.risk.score

        if (
            previous_scan is not None
            and previous_scan.risk_score is not None
            and current is not None
        ):
            change = current - previous_scan.risk_score

            if abs(change) >= 10:
                direction = (
                    "increased"
                    if change > 0
                    else "decreased"
                )

                severity = (
                    TokenAlert.Severity.CRITICAL
                    if change >= 20
                    else TokenAlert.Severity.WARNING
                )

                alerts.append(
                    TokenScanPersistence._alert(
                        token=token,
                        alert_type=TokenAlert.AlertType.RISK_CHANGE,
                        severity=severity,
                        title="Risk score changed",
                        message=(
                            f"Observed risk score {direction} by "
                            f"{abs(change)} points."
                        ),
                        data={
                            "previous_risk_score": previous_scan.risk_score,
                            "current_risk_score": current,
                            "change": change,
                        },
                    )
                )

        return alerts

    # =========================================================================
    # Alert factory
    # =========================================================================

    @staticmethod
    def _alert(
        *,
        token: Token,
        alert_type: str,
        severity: str,
        title: str,
        message: str,
        data: dict[str, Any],
    ) -> TokenAlert:
        return TokenAlert.objects.create(
            token=token,
            alert_type=alert_type,
            severity=severity,
            title=title,
            message=message,
            data=data,
        )


# =============================================================================
# Helpers
# =============================================================================


def _decimal_or_none(value: Any) -> Decimal | None:
    if value is None:
        return None

    try:
        return Decimal(str(value))
    except (TypeError, ValueError, ArithmeticError):
        return None


def _integer_or_none(value: Any) -> int | None:
    if value is None:
        return None

    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _non_negative_int(value: Any) -> int:
    value = _integer_or_none(value)

    if value is None or value < 0:
        return 0

    return value


def _risk_score_or_none(value: Any) -> int | None:
    value = _integer_or_none(value)

    if value is None:
        return None

    return max(0, min(100, value))


def _json_decimal(value: Any) -> float | None:
    """
    Convert Decimal-like values to JSON-safe numbers.

    Alert data is informational and does not need Decimal precision semantics.
    """
    value = _decimal_or_none(value)

    if value is None:
        return None

    return float(value)
