from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path
import re


_SYMBOL_PATTERN = re.compile(r"^[A-Z0-9]{1,11}$")


@dataclass(frozen=True)
class TokenDefinition:
    name: str
    symbol: str
    supply: Decimal
    decimals: int


class TokenFactoryError(ValueError):
    """Raised when a token definition is invalid."""


def validate_token_definition(
    *,
    name: str,
    symbol: str,
    supply: str,
    decimals: int,
) -> TokenDefinition:
    """Validate and normalize token creation parameters."""

    name = name.strip()
    symbol = symbol.strip().upper()

    if not name:
        raise TokenFactoryError("Token name cannot be empty.")

    if len(name) > 100:
        raise TokenFactoryError(
            "Token name must be 100 characters or fewer."
        )

    if not _SYMBOL_PATTERN.fullmatch(symbol):
        raise TokenFactoryError(
            "Token symbol must contain only A-Z and 0-9 "
            "and be 1-11 characters long."
        )

    if decimals < 0 or decimals > 36:
        raise TokenFactoryError(
            "Decimals must be between 0 and 36."
        )

    try:
        parsed_supply = Decimal(supply)
    except InvalidOperation as exc:
        raise TokenFactoryError(
            "Supply must be a valid positive number."
        ) from exc

    if not parsed_supply.is_finite():
        raise TokenFactoryError(
            "Supply must be a finite number."
        )

    if parsed_supply <= 0:
        raise TokenFactoryError(
            "Supply must be greater than zero."
        )

    if parsed_supply != parsed_supply.to_integral_value():
        raise TokenFactoryError(
            "Supply must be a whole number of tokens."
        )

    return TokenDefinition(
        name=name,
        symbol=symbol,
        supply=parsed_supply,
        decimals=decimals,
    )


def calculate_base_units(token: TokenDefinition) -> int:
    """Convert human-readable supply into ERC-20 base units."""

    multiplier = 10 ** token.decimals
    return int(token.supply) * multiplier


def solidity_string(value: str) -> str:
    """Escape a string for use inside a Solidity string literal."""

    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def generate_erc20_contract(token: TokenDefinition) -> str:
    """Generate a standalone OpenZeppelin ERC-20 contract."""

    escaped_name = solidity_string(token.name)
    escaped_symbol = solidity_string(token.symbol)
    base_units = calculate_base_units(token)

    return f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

/**
 * {escaped_name}
 *
 * Generated by HappyWallet Token Scanner.
 *
 * Token name: {escaped_name}
 * Token symbol: {escaped_symbol}
 * Initial supply: {token.supply}
 * Decimals: {token.decimals}
 *
 * Deployment is NOT performed by the generator.
 */
contract {safe_contract_name(token.symbol)} is ERC20 {{
    constructor() ERC20("{escaped_name}", "{escaped_symbol}") {{
        _mint(msg.sender, {base_units});
    }}
}}
"""


def safe_contract_name(symbol: str) -> str:
    """Create a valid Solidity contract identifier from the symbol."""

    symbol = symbol.upper()

    if not symbol:
        raise TokenFactoryError(
            "Cannot create a contract name from an empty symbol."
        )

    return f"Happy{symbol}Token"


def write_contract(
    token: TokenDefinition,
    output_path: str | Path,
) -> Path:
    """Generate and write the Solidity contract to disk."""

    path = Path(output_path)

    path.parent.mkdir(parents=True, exist_ok=True)

    contract_source = generate_erc20_contract(token)

    path.write_text(
        contract_source,
        encoding="utf-8",
        newline="\n",
    )

    return path