# Generated by Django 5.2.17 on 2026-08-10 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0003_alter_blockchainnetwork_options_and_more'),
        ('wallet', '0003_walletaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('token_transfer', 'Token Transfer'), ('contract', 'Contract'), ('swap', 'Swap')], db_index=True, default='transfer', max_length=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('built', 'Built'), ('signed', 'Signed'), ('broadcasting', 'Broadcasting'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=30)),
                ('asset', models.CharField(db_index=True, max_length=20)),
                ('sender', models.CharField(blank=True, db_index=True, max_length=255)),
                ('recipient', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('nonce', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chain_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('signature', models.TextField(blank=True)),
                ('transaction_hash', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='blockchain.blockchainnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='tx_user_created_idx'), models.Index(fields=['wallet', 'created_at'], name='tx_wallet_created_idx'), models.Index(fields=['network', 'status'], name='tx_network_status_idx'), models.Index(fields=['transaction_hash'], name='tx_hash_idx'), models.Index(fields=['payload_hash'], name='tx_payload_hash_idx')],
            },
        ),
    ]
