# Generated by Django 5.2.17 on 2026-08-10 14:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0003_walletaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.CharField(db_index=True, max_length=20)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], default='asset', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='wallet.wallet')),
            ],
            options={
                'db_table': 'ledger_accounts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36, validators=[django.core.validators.MinValueValidator(Decimal('1E-18'))])),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgeraccount')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['user', 'asset'], name='ledger_user_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['wallet', 'asset'], name='ledger_wallet_asset_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('wallet', 'asset', 'account_type'), name='unique_wallet_asset_account_type'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_account_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference'], name='ledger_reference_idx'),
        ),
    ]
