# Generated by Django 5.2.17 on 2026-08-10 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('wallet', '0002_alter_wallet_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('derivation_path', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_addresses', to='blockchain.blockchainnetwork')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_address',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('wallet', 'network'), name='unique_wallet_network_address')],
            },
        ),
    ]
