# Generated by Django 5.2.17 on 2026-08-14 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_walletaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_payload', models.BinaryField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_vault',
            },
        ),
    ]
